export const ADD_GAME_TO_CART = 'ADD_GAME_TO_CART';
export const REMOVE_GAME_FROM_CART = 'REMOVE_GAME_FROM_CART';
export const CALCULATE_FREIGHT = 'CALCULATE_FREIGHT';
export const CALCULATE_TOTAL_AND_SUBTOTAL = 'CALCULATE_TOTAL_AND_SUBTOTAL';